Updated the swift version of docker to 5.3.3-focal as Add distance(to:)  was added to Linux in this release. https://github.com/apple/swift-corelibs-foundation/pull/2890
- This is causing a build failure of the docker with the addition of Tau-Kit to Feather
/opt/feather/.build/checkouts/tau-kit/Sources/TauKit/Syntax/AST.swift:306:23: error: value of type 'Date' has no member 'distance'
info.pollTime.distance(to: Date()) >= context.pollingFrequency